"use strict";
exports.__esModule = true;
exports.ADDITIONAL_MEASURES_COUNT = exports.RULER_HEIGHT = void 0;
var RULER_HEIGHT = 800;
exports.RULER_HEIGHT = RULER_HEIGHT;
var ADDITIONAL_MEASURES_COUNT = 10;
exports.ADDITIONAL_MEASURES_COUNT = ADDITIONAL_MEASURES_COUNT;
